name: super_example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  common_library:
    path: ./common-library-1i4ez9

  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter

  super_library:
    path: ./super-library-5mglde

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  cloud_firestore: 5.4.4
  firebase_auth: 5.3.1
  firebase_core: 3.6.0
  firebase_database: 11.1.4
  firebase_ui_database: 1.5.0
  url_launcher: 6.3.0

flutter:
  uses-material-design: true
