name: super_example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter

  super_library:
    path: ./super-library-5mglde

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  cloud_firestore: 4.17.3
  cloud_firestore_platform_interface: 6.2.3
  cloud_firestore_web: 3.12.3
  firebase_auth: 4.19.5
  firebase_auth_platform_interface: 7.2.6
  firebase_auth_web: 5.11.5
  firebase_core: 2.31.0
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.17.0
  firebase_database: 10.5.5
  firebase_database_web: "0.2.5+5"
  firebase_ui_database: 1.4.3

flutter:
  uses-material-design: true
